global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic
clusterGroup:
  name: group-base
  isHubCluster: false
  namespaces:
    - golang-external-secrets
    - hello-world
    - config-demo
  subscriptions:
    volsync:
      name: volsync-product
      namespace: openshift-operators
      channel: stable
    web-terminal:
      name: web-terminal
      namespace: openshift-operators
      channel: fast
  projects:
    - eso
    - hello-world
    - config-demo
  applications:
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: eso
      path: common/golang-external-secrets 
    hello-world:
      name: hello-world
      namespace: hello-world
      project: hello-world
      path: charts/all/hello-world
    config-demo:
      name: config-demo
      namespace: config-demo
      project: config-demo
      path: charts/all/config-demo
  imperative:
    jobs: 
      - name: hello-world
        # ansible playbook to be run
        playbook: common/ansible/playbooks/hello-world/hello-world.yaml
        # per playbook timeout in seconds
        timeout: 234
        # verbosity: "-v"
  # Explicitly mention the cluster-state based overrides we plan to use for this pattern.
  # We can use self-referential variables because the chart calls the tpl function with these variables defined
  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.clusterPlatform }}.yaml'