---
image: quay.io/rh_ee_fcharett/pacman:0.1.5
# ClusterRole to be bound to the service account in order to access the k8s REST API from the pod
clusterRole: cluster-reader
mongo:
  image: bitnami/mongodb:5.0.24
  mountPath: /bitnami/mongodb/data/db
restic:
  secret: "restic-secret"
  repository: "s3:https://s3.amazonaws.com/pacman-demo-backup"
  cacheCapacity:
    source: 1Gi
    dest: 1Gi
pvc:
  storage: 8Gi 
secretStore:
  name: vault-backend
  kind: ClusterSecretStore
  path: "secret/data/global/aws-restic-secret"