---
image: quay.io/rh_ee_fcharett/pacman:0.1.0
restic:
  secret: "restic-secret"
  repository: "gs:restic-backups-rw8ns:/demo-pacman-mongodb-backup"
  cacheCapacity:
    source: 1Gi
    dest: 1Gi
pvc:
  storage: 8Gi 
secretStore:
  name: vault-backend
  kind: ClusterSecretStore
  path: "secret/data/global/gcp-restic-secret"