apiVersion: v1
kind: Service
metadata:
  labels:
    app: todos-database
  name: todos-database
spec:
  ports:
  - name: 8080-tcp
    port: 5432
    targetPort: 5432
    protocol: TCP
  internalTrafficPolicy: Cluster
  selector:
    app: todos-database
    deployment: todos-database
  sessionAffinity: None
  type: ClusterIP
