apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: repl-source
spec:
  sourcePVC: postgres-storage
  trigger:
    #schedule: "*/20 * * * *"
    manual: "backup-once"
  restic:
    pruneIntervalDays: 1
    repository: {{ .Values.restic.secret }}
    retain:
      within: 3h
      hourly: 12
      daily: 30
      monthly: 1
    copyMethod: Snapshot
    cacheCapacity: {{ .Values.restic.cacheCapacity.source }}
