apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: todo-jws
  name: todo-jws
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      deployment: todo-jws
  template:
    metadata:
      labels:
        app: todo-jws
        deployment: todo-jws
      name: todo-jws
    spec:
      containers:
      - name: todo-demo-jws
        image: {{ .Values.image }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - name: jolokia
          containerPort: 8778
          protocol: TCP  
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600