apiVersion: v1
kind: ConfigMap
metadata:
  name: init-mongo
  namespace: pacman
data:
  init-mongo.js: "db = db.getSiblingDB(\"pacman\"); \ndb.highscores.insertMany([{\"cloud\":\"Azure\",\"host\":\"pacman-5d9ccb4784-ftzpz\",\"name\":\"francois\",\"score\":9410,\"zone\":\"northeurope\"},{\"cloud\":\"Azure\",\"host\":\"pacman-5d9ccb4784-ftzpz\",\"name\":\"ingo\",\"score\":9390,\"zone\":\"northeurope\"},{\"cloud\":\"Azure\",\"host\":\"pacman-5d9ccb4784-ftzpz\",\"name\":\"martin\",\"score\":9470,\"zone\":\"northeurope\"},{\"cloud\":\"Azure\",\"host\":\"pacman-5d9ccb4784-ftzpz\",\"name\":\"udo\",\"score\":8430,\"zone\":\"northeurope\"},{\"cloud\":\"Azure\",\"host\":\"pacman-5d9ccb4784-ftzpz\",\"name\":\"loser2\",\"score\":940,\"zone\":\"northeurope\"},{\"cloud\":\"Azure\",\"host\":\"pacman-5d9ccb4784-ftzpz\",\"name\":\"loser1\",\"score\":790,\"zone\":\"northeurope\"}])"
