apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pacman
  name: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pacman
  template:
    metadata:
      labels:
        name: pacman
    spec:
      serviceAccountName: inspector
      initContainers:
      - name: wait-for-mongo
        image: quay.io/rh_ee_fcharett/ubi-netcat:latest
        command: ['sh', '-c', 'until nc -z mongo 27017; do echo waiting for mongo; sleep 5; done;']
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
      containers:
      - image: {{ .Values.image }}
        name: pacman
        ports:
        - containerPort: 8080
          name: http-server
