apiVersion: v1
kind: Service
metadata:
  labels:
    name: todos-database
  name: todos-database
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    targetPort: 5432
    protocol: TCP
  internalTrafficPolicy: Cluster
  selector:
    name: todos-database
  sessionAffinity: None
  type: ClusterIP
